### ISSUE TITLE
Responsiveness help is needed

### ISSUE THREAD

**Issue by Pasifista29** [Pasifista29/PriceTracker_cryptoCurrency#1]
I have worked on the website and it is responsiveness on the laptop screen but it is not dynamically responsive on the mobile screen and due to the time constrains I am unable to add the responsive part for the small screens if someone is interested in it can contribute :)

**Comment by adityapol41c** [comment]
I saw your website and it is not responsive up to certain range, so i would be improving the responsiveness and few things I would be adding, like converting into python flask and adding SQLite as a backend and a demo payment integration using Razorpay.

**Comment by adityapol41c** [comment]
I had made the necessary changes to the project and now the website is responsive for small screen as well, while I had also implemented backend part with database integration. Also, there was no scope in adding the payment integration so I have dropped that plan.
Hope you like the changes and if you feel you can add those to our project.
